# f1_widget.spec  —  PyInstaller build specification
# Fixes "no module named inspect" and other hidden stdlib import errors.
#
# Usage:
#   pyinstaller f1_widget.spec --noconfirm

import sys
from pathlib import Path

block_cipher = None

# ── Collect ALL stdlib modules that PyInstaller commonly misses ───────────────
STDLIB_HIDDEN = [
    # The ones that cause "no module named X / failed to obtain traceback"
    'inspect',
    'traceback',
    'linecache',
    'tokenize',
    'token',
    'dis',
    'opcode',
    'reprlib',
    'pprint',
    'ast',
    'symtable',
    'py_compile',
    'compileall',
    'importlib',
    'importlib.metadata',
    'importlib.resources',
    'importlib.abc',
    'importlib.util',
    'importlib._bootstrap',
    'importlib._bootstrap_external',
    'pkgutil',
    'pkg_resources',
    'typing',
    'typing_extensions',
    'types',
    'abc',
    'io',
    'os',
    'os.path',
    'sys',
    'builtins',
    'warnings',
    'weakref',
    'functools',
    'operator',
    'contextlib',
    'collections',
    'collections.abc',
    'itertools',
    'enum',
    'dataclasses',
    'copy',
    'copyreg',
    'struct',
    'codecs',
    'encodings',
    'encodings.utf_8',
    'encodings.ascii',
    'encodings.latin_1',
    'signal',
    'errno',
    'threading',
    'queue',
    'socket',
    'ssl',
    'hashlib',
    'hmac',
    'secrets',
    'base64',
    'binascii',
    'json',
    'json.decoder',
    'json.encoder',
    'pickle',
    'shelve',
    'csv',
    'datetime',
    'time',
    'calendar',
    'math',
    'decimal',
    'fractions',
    'random',
    'statistics',
    'pathlib',
    'glob',
    'fnmatch',
    'shutil',
    'tempfile',
    'logging',
    'logging.handlers',
    'logging.config',
    'ctypes',
    'ctypes.util',
    'ctypes.wintypes',
    'winreg',
    'subprocess',
    'platform',
    'sysconfig',
    'site',
    'atexit',
    'gc',
    'zipfile',
    'tarfile',
    'gzip',
    'bz2',
    'lzma',
    'zlib',
    'urllib',
    'urllib.request',
    'urllib.parse',
    'urllib.error',
    'http',
    'http.client',
    'http.server',
    'email',
    'email.mime',
    'email.mime.text',
    'email.mime.multipart',
    'html',
    'html.parser',
    'xml',
    'xml.etree',
    'xml.etree.ElementTree',
    'multiprocessing',
    'concurrent',
    'concurrent.futures',
    'asyncio',
    'array',
    'bisect',
    'heapq',
    'pdb',
    'profile',
    'cProfile',
    'timeit',
    'unittest',
    'difflib',
    'textwrap',
    'string',
    'regex',
    're',
]

# ── FastF1 and scientific stack ───────────────────────────────────────────────
FASTF1_HIDDEN = [
    'fastf1',
    'fastf1.core',
    'fastf1.api',
    'fastf1.cache',
    'fastf1.events',
    'fastf1.ergast',
    'fastf1.livetiming',
    'fastf1.livetiming.client',
    'fastf1.livetiming.data',
    'fastf1.signalr_aio',
    'fastf1._api',
    'fastf1.req',
    'fastf1.testing',
    'numpy',
    'numpy.core',
    'numpy.core._multiarray_umath',
    'numpy.core._multiarray_tests',
    'numpy.lib',
    'numpy.lib.stride_tricks',
    'numpy.fft',
    'numpy.linalg',
    'numpy.random',
    'pandas',
    'pandas.core',
    'pandas.core.arrays',
    'pandas.core.indexing',
    'pandas.io',
    'pandas.io.formats',
    'pandas.io.json',
    'pandas.io.pickle',
    'pandas._libs',
    'pandas._libs.lib',
    'pandas._libs.hashtable',
    'pandas._libs.index',
    'pandas._libs.tslibs',
    'scipy',
    'scipy.interpolate',
    'scipy.signal',
    'scipy.spatial',
    'scipy.ndimage',
    'matplotlib',
    'matplotlib.pyplot',
    'matplotlib.backends',
    'matplotlib.backends.backend_agg',
    'matplotlib.figure',
    'matplotlib.axes',
    'requests',
    'requests.adapters',
    'requests.auth',
    'requests.packages',
    'urllib3',
    'urllib3.util',
    'certifi',
    'charset_normalizer',
    'idna',
]

# ── PyQt6 ─────────────────────────────────────────────────────────────────────
PYQT6_HIDDEN = [
    'PyQt6',
    'PyQt6.QtWidgets',
    'PyQt6.QtCore',
    'PyQt6.QtGui',
    'PyQt6.QtNetwork',
    'PyQt6.sip',
]

ALL_HIDDEN = STDLIB_HIDDEN + FASTF1_HIDDEN + PYQT6_HIDDEN

a = Analysis(
    ['main.py'],
    pathex=[str(Path('.').resolve())],
    binaries=[],
    datas=[
        ('resources/icon.ico', 'resources'),
    ],
    hiddenimports=ALL_HIDDEN,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],          # Don't exclude anything — avoids missing module errors
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='F1Widget',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,                          # No black terminal window
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='resources/icon.ico',              # App icon
    version_info=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='F1Widget',
)
